/** Declaration file generated by dts-gen */
declare module 'get-sheet-done' {

    export function labeledCols(id: string, ...args: any[]): any;

    export function labeledColsRows(id: string, ...args: any[]): any;

    export function raw(id: string, ...args: any[]): any;

    export namespace labeledCols {
        const prototype: {
        };

    }

    export namespace labeledColsRows {
        const prototype: {
        };

    }

    export namespace raw {
        const prototype: {
        };

    }

}